<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ajouter Client</title>
</head>

<body>
    <main class="container-fluid">

        <form id="form" action="../Controller/controllerCustomer.php" method="POST">

            <legend>Formulaire d'ajout de clients</legend>


            <div>
                <label for="Name">Nom client <span class="star">*</span></label>
                <input type="text" Name="Name" id="Name" class="form-control" >
            </div>


            <div>
                <input type="submit" value="Créer">
            </div>

        </form>
    </main>

</body>

</html>