<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="./Src/style.css">
    <title>Stats G.I.T- Accueil</title>
</head>

<body>
    <header class="container-fluid">

        <div>
            <a href="index.php"><img id="logo" src="./Img/logo.jpeg" alt="Accueil"></a>
        </div>

        <h1>Statistiques pièces<br>Galvanoplastie Industrielle Toulousaine </h1>

    </header>
    <!-- <?php include_once 'View/header.phtml'; ?>  -->

    <!-- <?php include_once 'View/Include/nav.phtml'; ?> -->

    <main class="container-fluid">

</body>

</html>